ALTER SESSION SET CONTAINER = XEPDB1;
CREATE DIRECTORY dpump AS '/opt/oracle/oradata';
alter profile DEFAULT limit PASSWORD_REUSE_TIME unlimited;
alter profile DEFAULT limit PASSWORD_LIFE_TIME unlimited;
ALTER TABLESPACE TEMP ADD TEMPFILE '/opt/oracle/oradata/XE/XEPDB1/temp02.dbf' SIZE 1G REUSE AUTOEXTEND OFF;
CREATE TABLESPACE PFBIG DATAFILE
 '/opt/oracle/oradata/XE/XEPDB1/pfbig01.dbf' SIZE 300M REUSE AUTOEXTEND ON
LOGGING ONLINE EXTENT MANAGEMENT LOCAL AUTOALLOCATE BLOCKSIZE 8 K SEGMENT SPACE MANAGEMENT AUTO FLASHBACK ON;
CREATE TABLESPACE PFBIG_IX DATAFILE
 '/opt/oracle/oradata/XE/XEPDB1/pfbig_ix01.dbf' SIZE 100M REUSE AUTOEXTEND ON
LOGGING ONLINE EXTENT MANAGEMENT LOCAL AUTOALLOCATE BLOCKSIZE 8 K SEGMENT SPACE MANAGEMENT AUTO FLASHBACK ON;
CREATE TABLESPACE PFLITTLE DATAFILE
 '/opt/oracle/oradata/XE/XEPDB1/pflittle01.dbf' SIZE 100M AUTOEXTEND ON
LOGGING ONLINE EXTENT MANAGEMENT LOCAL AUTOALLOCATE BLOCKSIZE 8 K SEGMENT SPACE MANAGEMENT AUTO FLASHBACK ON;
CREATE TABLESPACE PFLITTLE_IX DATAFILE
 '/opt/oracle/oradata/XE/XEPDB1/pflittle_ix01.dbf' SIZE 50M AUTOEXTEND ON
LOGGING ONLINE EXTENT MANAGEMENT LOCAL AUTOALLOCATE BLOCKSIZE 8 K SEGMENT SPACE MANAGEMENT AUTO FLASHBACK ON;
CREATE TABLESPACE PFMIDDLE DATAFILE
 '/opt/oracle/oradata/XE/XEPDB1/pfmiddle01.dbf' SIZE 1000M REUSE AUTOEXTEND ON
LOGGING ONLINE EXTENT MANAGEMENT LOCAL AUTOALLOCATE BLOCKSIZE 8 K SEGMENT SPACE MANAGEMENT AUTO FLASHBACK ON;
CREATE TABLESPACE PFMIDDLE_IX DATAFILE
 '/opt/oracle/oradata/XE/XEPDB1/pfmiddle_ix01.dbf' SIZE 1000M REUSE AUTOEXTEND ON
LOGGING ONLINE EXTENT MANAGEMENT LOCAL AUTOALLOCATE BLOCKSIZE 8 K SEGMENT SPACE MANAGEMENT AUTO FLASHBACK ON;
CREATE TABLESPACE LOGS DATAFILE
 '/opt/oracle/oradata/XE/XEPDB1/logs01.dbf' SIZE 100M REUSE AUTOEXTEND ON
LOGGING ONLINE EXTENT MANAGEMENT LOCAL AUTOALLOCATE BLOCKSIZE 8 K SEGMENT SPACE MANAGEMENT AUTO FLASHBACK ON;
CREATE TABLESPACE LOGS_IX DATAFILE
 '/opt/oracle/oradata/XE/XEPDB1/logs_ix01.dbf' SIZE 30M REUSE AUTOEXTEND ON
LOGGING ONLINE EXTENT MANAGEMENT LOCAL AUTOALLOCATE BLOCKSIZE 8 K SEGMENT SPACE MANAGEMENT AUTO FLASHBACK on;
CREATE TABLESPACE MAINTAIN DATAFILE
 '/opt/oracle/oradata/XE/XEPDB1/maintain01.dbf' SIZE 30M REUSE AUTOEXTEND ON
LOGGING ONLINE EXTENT MANAGEMENT LOCAL AUTOALLOCATE BLOCKSIZE 8 K SEGMENT SPACE MANAGEMENT AUTO FLASHBACK on;
create role PF_MMS_ADMIN;
create role PF_MMS_BASE_ROLE;
create role MMS_REPORTS_ROLE;
create role POWERBI;

